baseURL: 'https://recusantradio.com/'
languageCode: 'en-us'
title: 'Recusant Radio'
theme: 'recusantradio'

copyright: "Created by WyrdThings & Blade of Maya for the Souls community |"

markup:
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  defaultTheme: "dark"
  disableScrollToTop: true
  disableThemeToggle: true
  postIndexTite: "Latest Episodes"
  postIndexId: "latest-broadcasts"
  assets:
    favicon: "favicon/favicon.ico"
    favicon16x16: "favicon/favicon-16x16.png"
    favicon32x32: "favicon/favicon-32x32.png"
    apple_touch_icon: "favicon/apple-touch-icon.png"
    safari_pinned_tab: "favicon/safari-pinned-tab.svg"
  socialIcons:

  homeInfoParams:
    avatar: "recusant-radio-logo.png"
    Title: "A place for invaders, by invaders."
    Content: |
      <div style="font-size: 20px;">
      Recusant Radio is a decentralized podcast about Souls related content and its community.
      Why not join the Volcano Manor, and fight with us? Rise with us, against the Erdtree.
      <br><br>
      </div>

      <ul style="margin: 0 auto 0 auto; text-align: left; list-style: none; font-size: 20px;">
        <li style="margin-bottom: 5px;">&#128251; <a href="/posts" style="text-decoration: underline;">Latest Episodes</a></li>
        <li style="margin-bottom: 5px;">&#128053; <a href="/tags" style="text-decoration: underline;">List of previous Guests</a></li>
        <li style="margin-bottom: 5px;">&#128227; <a href="/index.xml" style="text-decoration: underline;">Subscribe to the RSS Feed</a></li>
      </ul>
