name = "Recusant Radio"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "minimalist",
  "highlight.js",
  "search"
]
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "highlight.js",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search"
]
min_version = "0.83.0"

[author]
  name = "Rodrigo Haenggi"
  homepage = "https://github.com/therod/"

# If porting an existing theme
[original]
  name = "Aditya Telange"
  homepage = "https://github.com/adityatelange/"
  name = "PaperMod"
